# -*- coding: utf-8 -*-
"""CONTARPARESEIMPARES

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g4Avy5Tr4bt0nt4EGau6lqmgmIXcrJIt
"""

def contar_digitos(numero):
    """Cuenta la cantidad de dígitos pares e impares en un número entero."""
    pares = 0
    impares = 0
    temp = abs(numero) # Usar valor absoluto para manejar negativos

    # El bucle se ejecuta mientras el número temporal sea mayor que 0
    # Caso especial para el cero
    if temp == 0:
        pares = 1

    while temp > 0:
        digito = temp % 10 # Obtiene el último dígito

        # Estructura condicional para verificar si es par o impar
        if digito % 2 == 0:
            pares += 1
        else:
            impares += 1

        temp //= 10 # Elimina el último dígito (división entera)

    print(f"El número {numero} tiene:")
    print(f"- Dígitos pares: {pares}")
    print(f"- Dígitos impares: {impares}")

print("\nContador de Dígitos Pares e Impares")
num = int(input("Ingrese un número entero: "))

# Llamada a la función
contar_digitos(num)