# -*- coding: utf-8 -*-
"""DESCUENTO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g4Avy5Tr4bt0nt4EGau6lqmgmIXcrJIt
"""

def calcular_total_compra(monto, descuento_porcentaje):
    """Calcula el total a pagar después de aplicar un descuento."""
    descuento = monto * (descuento_porcentaje / 100)
    return monto - descuento

print("\n--- Ejercicio 3: Calculadora de Descuento ---")
monto_original = float(input("Ingrese el monto total de la compra: "))

descuento_base = 10.0 # Descuento inicial del 10%

# Estructura condicional para descuento extra
if monto_original > 200.0:
    print("¡Monto alto detectado! Aplicando 5% de descuento extra.")
    descuento_base += 5.0 # Total 15%

total_a_pagar = calcular_total_compra(monto_original, descuento_base)

print(f"Descuento total aplicado: {descuento_base:.2f}%")
print(f"Monto final a pagar: {total_a_pagar:.2f}")