# -*- coding: utf-8 -*-
"""VALIDADOR DE CONTRASEÑA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g4Avy5Tr4bt0nt4EGau6lqmgmIXcrJIt
"""

def validar_contrasena(contrasena):
    # 1. Debe tener al menos 8 caracteres
    if len(contrasena) < 8:
        print("Error: La contraseña debe tener al menos 8 caracteres.")
        return False

    # 2. Debe contener al menos un número
    if not any(char.isdigit() for char in contrasena):
        print("Error: La contraseña debe contener al menos un número.")
        return False

    return True


print("\nValidador de Contraseñas")

# 🔄 Repetir hasta que la contraseña sea válida
while True:
    password = input("Ingrese una contraseña: ")

    if validar_contrasena(password):
        print("Resultado: Contraseña válida. ✅")
        break   # sale del bucle si la contraseña es válida
    else:
        print("Resultado: Contraseña inválida. ❌\n")